services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=cro1
      - POSTGRES_PASSWORD=cro1
      - POSTGRES_DB=paperdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: